services:
  backend:
    restart: "unless-stopped"
    build: .
    image: backend
    ports:
      - "8000:8000"
    volumes:
      - ./project:/app/
    depends_on:
      - db
    environment:
      - DB_HOST=db
    command: gunicorn referral_system.wsgi:application --bind 0.0.0.0:8000

  db:
    image: docker.io/postgres:alpine
    restart: "unless-stopped"
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=referral_system
      - POSTGRES_PASSWORD=referral_system
      - POSTGRES_DB=referral_system
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./.schemas:/var/lib/postgresql/data

  celeryworker:
    image: backend
    environment:
      - DB_HOST=db
      - C_FORCE_ROOT=1
    volumes:
      - ./project:/app/
    restart: unless-stopped
    depends_on:
      - db
      - rabbitmq
    command: celery -A referral_system  worker -l info

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./project/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./project/static:/app/static
    ports:
      - "80:80"
    depends_on:
      - backend

