# Generated by Django 5.0.6 on 2024-07-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='money',
            new_name='value',
        ),
    ]
