# Generated by Django 5.0.6 on 2024-09-03 04:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_balance_created_at_profile_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='created_at',
        ),
        migrations.AddField(
            model_name='balance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
