# Generated by Django 5.0.6 on 2024-07-03 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('telegram_profile', models.CharField(max_length=20, verbose_name='Профиль ТГ')),
                ('telegram_channel', models.CharField(max_length=50, verbose_name='ТГ канал')),
                ('telegram_subscribers', models.IntegerField(verbose_name='Подписчики в ТГ')),
                ('youtube_profile', models.CharField(max_length=20, verbose_name='Пофиль в YouTube')),
                ('youtube_channel', models.CharField(max_length=20, verbose_name='YouTube канал')),
                ('youtube_subscribers', models.IntegerField(verbose_name='Подписчики в YouTube')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_blogger',
            field=models.BooleanField(default=False, verbose_name='Блогер'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.profile', verbose_name='Профиль'),
        ),
    ]
