# Generated by Django 5.0.6 on 2024-09-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_created_date_balance_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcode',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
