# Generated by Django 5.0.6 on 2024-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_channel',
            field=models.CharField(max_length=150, verbose_name='ТГ канал'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_profile',
            field=models.CharField(max_length=150, verbose_name='Профиль ТГ'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_channel',
            field=models.CharField(max_length=150, verbose_name='YouTube канал'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_profile',
            field=models.CharField(max_length=150, verbose_name='Пофиль в YouTube'),
        ),
    ]
