# Generated by Django 5.0.6 on 2024-07-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_balance_delete_check_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус кода'),
        ),
    ]
